ansible_become_pass: ENC[AES256_GCM,data:A7v5+epvca0/,iv:08hK3FNjdJakn5PX76H9pe7fN+OPwlcI/SpPwiBohh0=,tag:XRw9M4B7qdLzU6NAM86gUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhK0FrdDF3MHl0Q3daOU9X
            S1A4V1VaaHN1ZFNHUUN6V0ZMMGozbGxkNEg4CmVxWGk2VGIyY1pHUnhBL3NjbE5m
            OUR4Tzl1QlpoL1FiZWJrdEVOR1FDZjgKLS0tIHR4OExrcFdLZG0xM1JLV3FMYkF6
            MW52amV2NllVU1ErcjZsaWV0elhVUGMK2VvsMueRXZrTg5QCbXbpoPJollDdCUYm
            G9zprm2CZrMZpOEuYb0HhUs2rzgXYtsWLzebIbnPwTJVcQaSgt8Z3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T09:08:50Z"
    mac: ENC[AES256_GCM,data:V0bCi2kzZgoLLoJFFKDuNXUPB+Ah7Du5LJq6YYcJjrVGZXhArJXRIr/vBR5pkIPkRD7fyCB9fXnamZ8n6xh/pfMHttwY4F2qPkFTMtqqIhLBSsSkcLiTXk+BVc9KvHukE8kM4zFHobP1Gqvcwy9zHoHAvt4roScZcsh4PUZT9+Q=,iv:Pzr1GMsDz8HnQ8IfsddCzfiHwjY80dvyp1/Mv0+UZg0=,tag:6JvqKeWb8UEfkw9klGPdtA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
