ansible_become_pass: ENC[AES256_GCM,data:egyCCXn9uvTp,iv:uQOl1rMYS8im+WhkS0pygVBcwNyzApQERcBx8C+wpSk=,tag:wCEUL7ouGIzW2s7Bgxl7/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTb2tXMHFNYXYrNkFneTBY
            NWw3UjRKc0owWEVaOU1Ed01yWFU3OWQxT2lrClYxekErYWJ6YlEwRFo0MWNVU204
            S2wrb1BwT1ZwUklDQU1uOGlHOGovaEEKLS0tIDNqMjluNjNoRnYrbDFLODFUWXMx
            d2F0dTBCdlBiUGlKK3hMSG1qemJpYnMKp+Qwar22mfBsxJACA9rN9ry5Iisx+5H7
            zpBuc48rtmUDAjO//0s33Vvr8DgfcZWfGgdYxyCNahGGtVXNtR9Igw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-28T20:22:48Z"
    mac: ENC[AES256_GCM,data:cSQSIP05XovntbJZDUUyhu3pPtshMp0ej/BjU/a1KHEvltTp5Q6qgejNUACAwUVXEVGCXPwf/K5apvPNDTCzStlihoygf9i4PBVgsyNBjOVGM5eZfyXewaqeSNTsyzhQ+ocg1UycrgB3qO+JgjPI/XMaZhW/E0TyJ7j0hOgdI8g=,iv:BGF8J2UP1pc4Vv7czrlPlwkJZ+SeOIShHoMI0EaPzT8=,tag:64eOAZmWIqv+3uWug+2CRQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
