ansible_become_pass: ENC[AES256_GCM,data:7fvzqOm+ibCa,iv:CPLs1nWMZDEI3tNjZLc+Bwh8qpn5iDIoBjdFDMY37JY=,tag:7horiadcf2Mk4Rirn7eHxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOXhrSzVvOUNmMXlCa2x4
            MmxrbHQ5T3BoZ296d2kxNkNWMHlDdU52ZEJzCk51Ymoza3p0WGF4M3Fab2EyQytX
            NVNTYnk3SG1xdTZaeE5BUE5MSFJUUXMKLS0tIE9mc0JyOVBkQXJGZGZTVFdpRHpZ
            ZXlzUDlaa2ExZzZWNS9tNUxCR1A4djQKNKeFNmLGxq/rNCHcq9kU1oQRQm4zSAjK
            uIkOYaDud3/08YbBNnViR31txwwzM/SCxnUpjxoe9YaGoI3DzRfitg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-28T12:52:05Z"
    mac: ENC[AES256_GCM,data:I2OxEeSV2cS3yG6OeaUEwwSXLdkHUBPrtdyVAHO5N/nlyofJxpihOEuArE209r+/s9Tl1wh0kfUFZE6N9NU0Heo913FkLT6alfMzNQAfSMuzaKowVl6sS7AKRBcZwIJbtcHfUSpbDzkefgwBBKsVrTLSMOvLZZoBZwj9JGu5lNw=,iv:bF3z6M57gAqPGpTtaO86FnGO9OSICAaiMDp38iudOvE=,tag:2WiKmS2jUivfn1CtlLkjww==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
