ansible_become_pass: ENC[AES256_GCM,data:j9EsbUP+yz6Y,iv:ZJgq5Nagv2TcXj9MW5dkI/Tb7waISziBuNXw33d8MiI=,tag:/q0SKw0WysDyYs6srZxCSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxY1NlRVhuUUk2enhzZ2tM
            M1l6Nkx4bkZkUW5BZk1Qc1Y5ZzR0eGpHamhFCkluR3JWakdiUWIxeU5Eb3RkZjlD
            M3g4UlVnRjEzODBSenh0ZExmcGxNaE0KLS0tIC9ZL1JzRVVwcWhvUkMrbEdCKzIx
            QUEzckFXb2V1cExWL1R0UndGaDRMM28KvplKB4ZWCOnOCtH23HIkuJ+d5I+k6N+f
            eJWiAzw8IjQKH4DjCPsB4qppUhD7s/48Y0XXIGCzT9WeUAzYcw5ebw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T08:53:22Z"
    mac: ENC[AES256_GCM,data:kC1eHxmnFjfHleyQIiKc14LfZOhrl9T3mHTZou+KjZIH3fvGqi16Z2p0RhKtguXfJL/eToBi1ikRXY62AbV4Z3CYWiLDw626FYL/ghDLWA242+FKtiWh4JxWyh5V/v8KmfHdsh9sqyGmrk6+WvILA7lXOq8/S4XDTdM3qsVPFtg=,iv:Iu3z8yEZLQSvD8EsshftHibUGbb/1ue3i4AJREPr6+o=,tag:7mdqlC6OwPa7ltcJi65gYA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
