ansible_become_pass: ENC[AES256_GCM,data:D3u8JxVmxpWd,iv:wULw6RDlvQshLUYHwGuiEloXxQrVwWh1lRzfO3PMHyw=,tag:UTqCPk7zD6lay/uorOVFnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSjFiTEZ6amNSa0hxVzB4
            Qk9LRDJmVThNMDJEcG43YkwybHVVa2VyM3l3ClNQTzBUQk9rdncrbE50TTZFS1Zm
            ejhqRFBYbFdzdU9nMkkvemdmbkRqWHcKLS0tIHBHZndUUnA5dHNwak9FZ2hVYmh5
            ajhzVGdhZmpvMFo1Y3AxUUVNNGRsMVEKygnxnyNzQ/uk2aIOu8WJxVeQ2IW4Elc6
            hk3BAdCRcE3TkQZvJLCELJ1dgEHCwC1/dAssCoO8e5AK9bxcpaE6RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T14:16:40Z"
    mac: ENC[AES256_GCM,data:Sgnr0qJMcugQ1hN5JBslLtEMYbXl3ai3k9rohBc6ggVj7UNnNWiatF/R/roNrY1Y4rOAhusljdEzPq7l+05/gXx/7HICxQ4/C1SqXNcgd8FyLI42FUzty7TnEYwvA6Af0SRyn4gHrN/KOavttFdzH6ZTvMf7WPZfbo+jZaK9Rdg=,iv:PgoIqdOTar4gqW2MpzN7MnsVJvAT+wYaoC4SbfzVEV4=,tag:hnTNW2hiNt3LUcSiLamP9w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
