ansible_become_pass: ENC[AES256_GCM,data:fEK6AlrfKaJ3,iv:e+RfDamYCKge4IxCop1Q1docL2aFnnYZFM+p3BY9/J0=,tag:cdRRKXxliVSQopMaxXRtKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbmt1b0lMSmNLWGV1alp3
            a1BVRFFvYy8xT0s0OFBtdXVVTCtIUmVYbUVrCjVWRDdpWmVKNlNnS01Cd3NZY1Iy
            V2xsZU9XUDZOWHRGMHJqQ3V5bFZLZ3MKLS0tIGZGRWFYbWdqWXRlaWt6TnJzbmYy
            UWduc1N5dDV4NUErSzk4ZmNCNXNQdXMK3fME9ruPRCOcZ9TaQ5A4i1pdN4iOTK49
            U/kMKPnlUjrMylrniO6eT60vr8Me46GvO2hLqcEhgSSb0Ddbbq0ELQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T08:43:44Z"
    mac: ENC[AES256_GCM,data:7/8aK3MU5BMiw6H8evSXAldXemzBxwOAyagoc8+Ow15x0frIWW9DGMUzz7wGevQNPSo8thjhOMI3yhFjz6nSmE4QhKu+sNEKLtoYDzruF9SOLRh7/LCeGW+ANUOLiZ+lYfvC5hiAzCH06o1yRFBqNNW6joImhSuKI/6ISePqtiA=,iv:AY8WqfEfvmJMKtvqJVbyHCqVrbf2ll5BwhLBk4BCP1o=,tag:aYm2kTmtpCF0ktvUtHPo0A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
