apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:EA4bCdQ/DXpOEp2timp8+MRpO2Y7Z8ZW,iv:0soqfiOg7gTTjazV/aSDfIYy7EmsznmIt6sv6FeKMWQ=,tag:oGlb8Z/Qf9QqZ+eTGbyzpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWFFtOFFOeEJVMWtDdjJa
            ZkNFOXg1UHhZd3U2SktWNjZnV2xFeDI0RFVVCktDditvNFcrdC9ranAwUnovaUEr
            TC9kNzZNeTY3MWl1Tlk5eDBBNXN6Z2sKLS0tIFM0Z3pIRHBBS2FsZUFZZG5mOHlO
            dit2ajdPZFcwQ0hRQUVqUXA5Mkd6MTQKupgeIOO3OZPYk/tKvFCKhy0njpKdiy/1
            qI5mtpA2pbvjmBRwXmROPEvOD++3U4N1AXW8K/Z/B9jfrQ9ged0YkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T14:38:27Z"
    mac: ENC[AES256_GCM,data:/e3dh69BgmaIUxgZ8SRuTiVNTDNxTFM64qDgT5Sjny5+7rE8T8Ev7G6pkdF9u+oNyIzKa18A27rE2VcXjnCLBJYBvi8oI8/1tqSI21oyncWLhOmUd1F2Ls++uI3mflvYXiz6iwtPLYR0pSqdRV3rCc7/DM7eyO1eG9g+6xM6WD4=,iv:5YZc+xz2FGKD3nWwbymXx4MI+MyhetryqPIY9zMo914=,tag:CKneRX1jkio09p48ohncug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
