apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:jl7//7GvLzgMMHxVNOH1gprkf4OElHzn,iv:npE0Wq2wQNWmYdNhPvetdk5MXYhStKQIMH3voOnlcxw=,tag:HD1Oe1vh5/5JvBRUSUlW2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OE9qeDBJQmpobzJIbEd4
            VUlKd0FtSWViMmZBd256YkxyUExWZWlNUkFvCkRibEFYcm1CM0l5cElQUUQyWk5w
            Ry9WQTh0c2huUXpyV0hnbHVoZ2ZNRGMKLS0tIHlxOG1OdVlTTS9ieWZYWkZWNkhW
            bG1MeTdIQStrNU9FSk5UNlF6U0w3WWcK9gOLHZl153aWYe2/M15n4iyCJw3Zohzd
            LJiEXhMRj7MX+8xVWO1xCUv8DHL/yXCSwk6iwUEtCuf4JISot/VOJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T08:44:51Z"
    mac: ENC[AES256_GCM,data:wC1WLkRDQ1glIkJ/mRQTVS1mibDPTpDlzjSL6SGcqQ76+a3/w7xAaNCIjsjJL/FRy+bqkEVERhZnJ5avsOr+AMA/69W1aFBVrtF6dGEgPIwyIt0eqjrI9huZ84qV5mc/Nd/RkGKsbjuuXw5ml5PNzL82mOdTCwAC4Wqo10zZb+Q=,iv:rGeScjptkchf7MHdekzd7EZ4mIgU9bExGeTRCikrFlQ=,tag:LbEjJH46FejNi9ISVr0rFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
