apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:6dF/PScz4HOCxAaCyZxu45rvk5Sy4A+x,iv:cnVm+AcTrD1pO/3kpx4gCAsuVkzgTKgw+ZQ2HapViig=,tag:wCVB2nDsa70DfztCrFfUeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRzJNeXhBM3VKQm81a0l0
            V2J0UUkzakUvcklzWnVVbzhiczU3NUFyK0N3CnJKSmpna2ZBMWZOejhaUjVoTzlz
            MURKc0haSHBVSUJaNHg0aUNzeU11NzgKLS0tIDBCWEF6ekF3WnNxS2VFc2laeUFK
            RGdyanJFQ1JuL2VoNS8reXRudW9SZTQKrIapDScc41nc+bZy7O+X3KqCGRv/kG8l
            //gS3pOcFwKP3M8FTGJLZygLl84UISD207BKjZ2ldxXOvzafuzwe5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-28T12:53:16Z"
    mac: ENC[AES256_GCM,data:8GqmApugSXVEi3uR4mJXzZj/W+McFJeGNulKpypGynyAMdp89tJzVdWtAhIFQIRt68AGmJwgEfKJjNpxmx7XNJG6mwsZOx1WfS9jWQXpwj0yhen14GFOjGkCn/5+EQ5ACAAYvA9tkOUhDsymbiOIDQHnOF4O7fNinkoItg+ZAQw=,iv:vfqDATYxLqj+3gXmauzRa2tUVqSSfjFX1q5HXQpapFM=,tag:Bd7hSKqMxienr4+TYSgJqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
