apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:usIr+MPPDx3CooLAt2GwekKJ7AEcBdpJ,iv:qnyF6ymdDTjFUeI0ZMXavY+Xx6SU6iKx1tF3WxjE+oE=,tag:ud9943vaJrpyPXNh4Oxo/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bGkybUY2em5BbXZPUVJC
            RnpKSVo2dFdqaFQxYjZkMG5ydFRnWUFEZW5VClIvL0RYMWZ3NnNnelN0cmNJLzIw
            T0lDQko3SCtnK2x6ekl4UlJSMXhSNGsKLS0tIGU3bGU2enpDQXdoREp4QVlJRnNR
            L3llMDl3dDdkaWJGWHlzeWpiLzZGM0UKCHDbsoQMmbD2wMb/GB5QNIGyLI+fB8/i
            AsiorRLsfeZhCgOzx7VP39NB//n2e+UIuV2YcTQNFc3+Qudx9P39nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T00:07:41Z"
    mac: ENC[AES256_GCM,data:m0poNEmggRX6meBmWv6A1ajAnJ4eTV2fbHZS6408m0weoC0I/KDrntQiIZxEkG0BXTUDsvDHD5OxgkwpRCg+N6KXmkqt2Sn9mCwRhxcCA7NBLxcinQeFMCeU4ciJ7Ms67hiyR/u2GC5AxnwX4lbCZ3W8i98v99iEkkHg8dCn/Y0=,iv:l8LsCUs3bztgQ2CCqVRZNoJV3BkyzW6aFa6EIFp3m0c=,tag:rp0z67LTJKXSB8hFGuS2YQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
