apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:rrvS3siR9JVA7DKlMBRGdSyx1dByIucE,iv:OH6mp8m8YnLEwo9/cy4Pg+nGBNdWjz6Frvf/SZ3p6W8=,tag:XrOqJLQq2HUFCVNfIqiNHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYkMyRkZYRW9MZzJaTXVq
            WFdTRm5ibDY4UG50ZElGbHVWZ3ZmWEd4SzFzCnJhUDVWUllkbm1mVVdpUjQ4Sldn
            ZmJTcEdOYktlOEFwMUdmV3RiSlFBS3cKLS0tIHdKa2l6L2ZUeEJLV0pXb2E2bisv
            YnVmRU5hL3NNVFlyeTBKQW1kTzlheE0KGZvKNlhy1SNm5oGJqsiOS8hz6n/L/Lje
            KbFGWiEqDTAmfDuJImq4Ck2K2syCcd8FsH349JYQm7869pF2d7S/3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T14:13:58Z"
    mac: ENC[AES256_GCM,data:uBR1ktVzja8HM6YALdD9swG3cWq7Xrj+3U//fFqNXZc0pdxx3sthMimypybvcaryA0qiWUTxj2mKbVzilqna56YJyn2se4VF54CmgH4irarqz+RwjSGijiQ2to3FqLUyJF+A2PjU9BDyrUEgYdUVMHMbTXVRhCKo80zh08h5cRA=,iv:0Nfkg9eSiuZoNTaR/ARSw/DmQOytIOGHQevWrF3KuK8=,tag:837X8zO6T2lYMiSIWWEf6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
