apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:vyjwbS+hT5wH5Xp9l5Q4bsBHuQmhLZWG,iv:k74E517cm/CDSxx8qg9lHoX71pHXFU5DgkGuJW1gPpQ=,tag:CMYRHzWsRt3ghveZFTdV+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOXEwL1FJTm9ITkVhTHlI
            V3hBbFUyY2pjTE9EMUNlc3ZDQXpjdHFjTlZZCmlDNDVFallFVSs0Q1FzRWFsMHdx
            WUNUa0pJV0lURCt6eEIzZFZKakhBY1kKLS0tIFVoWG5CaWsxeUoyL2g3d21tTkRa
            ejJGVVVqR3orbWIrUkczZkYvVFdZTEUK/X3gJwkJ1DJJ2rLYtiVm0vMqtm/pomqE
            CfQg9WFQLaBZbgf5yQo3XeGgjT0zRGv5yGAIJX0+V0+bfq1C/RCr2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T14:47:38Z"
    mac: ENC[AES256_GCM,data:ie431l2eJDgQETqemCcCJe1ZAmLNmBpdrD8qs5v8CkWcPNqrWHVkry2O7tw7xw2BFbNJ5VnQc3tuCd31MJ8Utxdei3scK+PiEFZ0Fl0X1Wy49OyQ6/i6up/RJhyRED86CRR2mapdU7dNsbN+JFUuWHKMAFSm8WdzgAfpAzLKsKM=,iv:E1LCUBXsoO+5cLVJUYyZOAGCfvlPr60sSYpwEkM/g9I=,tag:eyOP2IGd0R0kxzQF/VgiuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
