---
kubernetes:
  children:
    master:
      hosts:
        node1:
          ansible_user: dimatha
          ansible_host: 172.16.172.221
        node2:
          ansible_user: dimatha
          ansible_host: 172.16.172.222
        node3:
          ansible_user: dimatha
          ansible_host: 172.16.172.223
