---
web:
  port: ${CUSTOM_WEB_PORT}
storage:
  type: sqlite
  path: /data
#   path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=require
#   caching: true
metrics: true
debug: false
ui:
  title: Status | Gatus
  header: Status
alerting:
  pushover:
    application-token: ${CUSTOM_PUSHOVER_APP_TOKEN}
    user-key: ${CUSTOM_PUSHOVER_USER_KEY}
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 5
      success-threshold: 2
connectivity:
  checker:
    target: 172.16.172.1:53
    interval: 1m
maintenance:
  start: 23:00
  duration: 1h
  every:
    - Monday
    - Thursday
# endpoints:
#   - name: status
#     group: external
#     url: https://status.${SECRET_DOMAIN}
#     interval: 1m
#     client:
#       dns-resolver: tcp://172.16.172.1:53
#     conditions:
#       - "[STATUS] == 200"
#     alerts:
#       - type: pushover
