apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:kS8d+zQFOOzcC4QBaEoz2ZkTP5nhOKCLMJAv4ry7BeKQ433QxcG7LQ==,iv:aBPVBvi663+wgRW6Syq3A5jWuCQmXLiEJ/irotXH2y0=,tag:Ch3YAI4ZAXt/3DJfWGgKlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVW56N2VFY28wbjJWdDFC
            c3dYamxXbGdnSnE1NkpKcDN1RkVucEZGalhNCnRaSDJYeHZLclBWTjZ0NVBFWHZR
            OHF1VWlQTldmWG80WDhMaXBMZHA5UXcKLS0tIHF3bkI1MUYveG1BN2R4TS9nNWVM
            c21lVXdabGYvL0hvRzI0UkdjaDlZK0UKislrR5OPilwImQmtoMZCwDkazB3mk2Tt
            rmGcfrR0GCGLpCjJ3dEzkMqZ6dnO9Eys5T/ySy930nGmQCHdkWXcdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T08:44:52Z"
    mac: ENC[AES256_GCM,data:hlYQjSipr4XD1d27Z+QJFeM4T3i44lmmp+qPOYDdeIfu80cdROukIswRjieA55qZVnKx3ilRoBdzkUlA63PilILE/XDMP9te1NvOO5THDPv0LkkBPMH4C9A394YE/4Kn6yAF+vHPWGizh9SOU0FW6B4KERx/6pu2wOesMo1n+/A=,iv:eLqMGzmhm6HbArlYKsMjRbW6ladyPfsYHAD1FG8I+bQ=,tag:02ewpy1APQdYWvdny5p5Bw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
