apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:bc7MacN/ZrlfL0mFgEvG7Z9YipZxsrqGPEa6Oxp7zDBE6GC1riMEVA==,iv:0iBBiDF342dIZaRezf9nmDSO/qWVu7VCF+KOJl1tZmM=,tag:VUEhJPRZYDpHIPm08Nhzug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJN25CbHZPNm9WVksrNHp4
            NFhnMkROZEU4Szh1V1dsSThrZnhsZCtvT0VvCmFGT2s4RmxmMjk3MmZzS3d1MjRO
            eHgzNzl6OHNldmFoMXlnWVdkQU1yRjQKLS0tIDZSdm1jYzNLc283bEM1VUdCTUVZ
            SUVacUV5UW05c2ZkdGduelZtdlhjTW8Kurc7T1I80MXWb5Wizmewm5MWgRf1srNW
            xK7x3nYI95wvbkOui3hIcznl6CFNfqLrSQfnbY0uApJlUYFcSFC2pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T14:38:28Z"
    mac: ENC[AES256_GCM,data:fFc0c8oTjbItXQaP0V004XeCde9bNhjXikQH7gjUE3Mvyn7i9LjL0GjfwwpuDpyg1f/3nBFcUDPxI3zVUt4LRTc++c9qdtHasr+LNxggtf/c5Ln6ErQ3KTbZixh3ZB7IXOx+3Ef9eXbKFZs5WXr+GsmTQGZLBptke5yAopXFu0Q=,iv:8QxLMg10MOFl/v+Tff4c6aagW7vycGorpu/sCuPRmVo=,tag:pEpCYNaXD4rIhDfJjMl2/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
