apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:T4L+knysU69BzYa3TwLzPIIKDIp9uTihJIeNFujfEh4YnsePjC+jrQ==,iv:nOqoB0+fZWhAXLW6suhuFoc4C4y8q9UVzTFT9vXfegM=,tag:pRgKcTO2ZaocChXCVC4jEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNTR3NVhHb09oa09DOVJ0
            MW9xQ0htWng1M1J2R1NpSGJ5Tm5kclQ5VTFrCjNvOXlCdElQNkVtSnZyVWovQU1y
            N3plWTh5bFN1eHBLSGFTTnVMcTg4MHMKLS0tIGJ5UlhxR01RQkN4VlErSllMdFl1
            aVJ1dnhNeXNVUnl6NTVaWWhsNUF1UjgKXJ/8gzyFYCumJJhHTkDRZbKJ1FPPedV2
            yJmU47MEGALef//2/3x7q7L3o0b1hahaV6hVM859pF8ymH12czFShw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T08:54:32Z"
    mac: ENC[AES256_GCM,data:bf/JXqTA/7Br0VfJicxxv6LtNokthZkCqUMP2B0jbhBrhSuoBOluxEZX/1i0I+q7HswnlUw4+/32MD/AYsEq2nz5n8dea7135i8a8bE7jVM2GuJ7JYgY3c8wNGOTgVix0kTbpwviz1wczMbuhSh/iW/xeXed2suzYm2Xe/cf72Q=,iv:1upYHC41+M+UlJohy1/IaMGnhzMru697sT4eWT6PTUo=,tag:ZLMhNddPcpAgE6s3ok9crQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
