---
session:
  redis:
    high_availability:
      sentinel_name: redis-master
      nodes:
        - host: redis-node-0.redis-headless.database.svc.cluster.local
          port: 26379
        - host: redis-node-1.redis-headless.database.svc.cluster.local
          port: 26379
        - host: redis-node-2.redis-headless.database.svc.cluster.local
          port: 26379

##
## Regulation Configuration
##
## This mechanism prevents attackers from brute forcing the first factor. It bans the user if too many attempts are made
## in a short period of time.
regulation:
  ## The number of failed login attempts before user is banned. Set it to 0 to disable regulation.
  max_retries: 3

  ## The time range during which the user can attempt login before being banned in the duration common syntax. The user
  ## is banned if the authentication failed 'max_retries' times in a 'find_time' seconds window.
  find_time: '2m'

  ## The length of time before a banned user can login again in the duration common syntax.
  ban_time: '5m'

access_control:
  ## Default policy can either be 'bypass', 'one_factor', 'two_factor' or 'deny'. It is the policy applied to any
  ## resource if there is no policy to be applied to the user.
  default_policy: deny
  networks:
    - name: private
      networks:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
  rules:
    - domain:
        - "*.${SECRET_DOMAIN}"
      policy: one_factor
      subject: ["group:homelab_admins", "group:homelab_users"]
      networks:
        - private
    - domain:
        - "*.${SECRET_DOMAIN}"
      policy: two_factor
      subject: ["group:homelab_admins", "group:homelab_users"]

identity_providers:
  oidc:
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: grafana
        description: Grafana
        secret: "${SECRET_GRAFANA_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: one_factor
        pre_configured_consent_duration: 1w
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris:
          ["https://grafana.${SECRET_DOMAIN}/login/generic_oauth"]
        userinfo_signed_response_alg: none
      - id: proxmox
        description: Proxmox
        secret: "${SECRET_PROXMOX_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: one_factor
        pre_configured_consent_duration: 1w
        redirect_uris:
          - https://pvec01.int.sakun.in
        scopes:
          - openid
          - profile
          - email
        userinfo_signed_response_alg: none
      - id: synology-dsm
        description: Synology DSM
        secret: "${SECRET_SYNOLOGY_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: one_factor
        pre_configured_consent_duration: 1w
        redirect_uris:
          - https://sakun.myds.me:5001
        scopes:
          - openid
          - profile
          - groups
          - email
        userinfo_signed_response_alg: none
      - id: pgadmin
        description: PgAdmin
        secret: "${SECRET_PGADMIN_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: one_factor
        pre_configured_consent_duration: 1w
        redirect_uris:
          - https://pgadmin.sakun.in/oauth2/authorize
        scopes:
          - openid
          - profile
          - email
        userinfo_signed_response_alg: none
