apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:gdSvKRW5dGG0Yg==,iv:ofnRjTTpCyrNsKuF/I9NRkABQu/BaLYBqCK/hLrv1E4=,tag:VIPmf6TN85mtKt3rP/cC5w==,type:str]
    userKey: ENC[AES256_GCM,data:wc/439oePCoH4lDvQrQvd3YnZ5HryW8FMaL/GrLuA4m9O4k/RFZ6Iw==,iv:Z2APoQ9n7pmdyr/694BVKLAsDvyR14MHgJHqCIFiOUI=,tag:szdZ62lxdnnYktD7bnT0yA==,type:str]
kind: Secret
metadata:
    name: csi-rbd-secret
    namespace: kube-system
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpazI1VU9IdEorRmdpQisv
            b0svZkRRaDMvRkZzMEtWdkIrOElaanZQRDNvCjZxc0NVNlRlYUg0cDA5ZzhEVzU5
            MndtRE4xUkdvQytvNVJCQk9jQzRyUE0KLS0tIFRkV0pNRnpqMS9YbGZUb21FQjd6
            VklRa1J2ZW8vOU5BRUpldC94ZkRpOWMK2HfirzJU8+O/ma7ejgC/lDYZ/v3zYAym
            DAo0YTYsLQvKJHXfiTr78bNGGHSwMUChvl/BtvM4LA7JOBvVSOUg2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T13:58:03Z"
    mac: ENC[AES256_GCM,data:7GpDH2FuBLlSn4oZZkIUocN/Dfz6hMBR46gAFP4/4d7gH14DtRmewQljH9rPD1Ba0Nq8xSQxTl83Wwpp00/1TuboDIIw68xdX0BdyBwm/3j3kUfCP2cpMziTprA6M3Oem1a2I3PISl5NvrFjylRr0S2m3wO8PLqBb9rjHJ63O/g=,iv:umtMKx66udVN675XR05dBixClh58MNPpMe2r7koIUls=,tag:gsad6da87ieh54fY3PQgvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
