apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:R6ocBnj/gLuvRDGiFW8f,iv:Hoo7jiitwnMY1KmKmKp08iwccdyh86furDkt/7LTvsM=,tag://Xg0LBgdLsa6MNu1E5zhA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:FjQYzuNMnft8jIjUipDUEHn/ZT6JDD8IOqn0HKQBjyqQrb/I,iv:vqVqolFf6LIlRfx4ngP/JnHC/uXljziZpxEG083vjMw=,tag:NjayrDVs26WovoW+6SvjKg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:iy1SiiHAOs8=,iv:rpWZozmmduqqWroyOQqA7i2fhxxwkxVVBhlRMKuL5/E=,tag:pPdxLlywaKwBLL0QBll7Pg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVmgyK2N4TldXcTFJYXdR
            ZVFuMmsrZjl6Y3JKam43YW14RHdPaG1NQ0Q4ClpNU1lDMFZHQ09LNXI0cDRiMUdT
            VlQvY3FoS1E3M0dTaHR1dE9TZFlOUzQKLS0tIEtsOGRoK0FJM01wUkJYQm4xci9J
            cVgyWjJEMDgxemtZblVXRytpMXBTQUkK/hp3+K9wmmiXDjHMD6jaVXppVjuZU34Y
            4D4FBSKlv3GCPbTTY6gHdFPaunP43uQunpqQ5jtfjqsHzPMBzLoRLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T14:13:57Z"
    mac: ENC[AES256_GCM,data:90SkbFjofn6XQAqVt/zPVwC8hiW82eWpgP5WS1YlQGcsBYCXHxUEd0crbCYyds2V1PskS/p57DbS9RcCdbo5wj1qZrsjDZSDkSGI/30+BhMpzZKA3gA/Sjf0wgxNpGaHCCdvKE9y4g6S73rwgQO2TNUxr7MCtrfd2PQjCr0MWGw=,iv:8iyqvTvLq5yGVP5eWEWjP9LqqDVxZKcDjYA87pBpric=,tag:HUSaaxBLBNO/HyjV1A5wnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
