apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:NHyp0tDuLkMiSIrtadtR,iv:zwXrLw5SISUUjzk5mWX2ikBj9nUf29CBHGlepmrOKSg=,tag:UELBxKtVYkOK9yFPVsjLrQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:F91ZVmHRLYQcr29fC4K/61ED3nJP2tDP5acu1JR9PbPjblFM,iv:nNzyP8mT2+oxs8dX5qfv+lXCgwvj3LDkBVywsa8InAo=,tag:rwguZOLdek10c6v2UGf4gw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:vuKVFaLMGlI=,iv:RKaBcoPdb4YYzkI+4w+65tmzu5DUXB9SCOQ/UfLx5to=,tag:z6Y08SGxlRTPbrQtH80ZnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VGVJZG51TGlWZnVaaFlj
            UTJvaVVhbGlPMEZEMTVZOE5jdGRxUFdGb1IwCll2OG81SzBqU1l5K3lFM3dpVStD
            OVBObEpvcXptb1VyeVZxVnkwUFJUZ0kKLS0tIC9LSzN2azgzVHB0bFQ3azZ2SFJs
            MlVVdnlyekdZbUJxRjN6WTQxa3YzWVEKwzKVBLIDa0DgzxVP3YZhO+wt1FOKo/0X
            jyCVZgxBjOaJDHNDkE51/COa1WnAuX3q2CzTQ4+OKFDVPj6xQfDs6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T08:54:31Z"
    mac: ENC[AES256_GCM,data:R+xat+7YujlbaoRmQs2AdHSXF6+xanuOMk2F/67OKcIuIYgd8ZbCiXHoNaxtsRO1smVTf0/rDjF9gOZwvxpw6mbiOUpZMT0CDWoBJeCE/3EUeiMl4w1yM2xKeM2XKYENUaDFVqRcKRvkHaZ9eTA33XWY3nTFX16OaIUy5vBx6jQ=,iv:S7GuYo+5ivi0H6E3V7ypTigxUnMPNV2dAnuNMvkTXV4=,tag:FSdTyITZ4HWxnD7Jmbeg0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
