apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:a5sRVx0Ml/3GUap6,iv:6rdON8fDx7eZbvy/FUjQ9vHwPQ6DZgU3OGT1ay2yfFw=,tag:uMw3GpaeJif4CgeUhmbt1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOGtGUG0yNGh0MThpWTJ5
            T2YwM0c1RGs0QUFqRkVyeXdhaVAvSU5TaFdZClhKWTVSL1l0TmxBZHlyczJMTkky
            ekZRUnFmUkFJUmduRC9STW1CQ3ovWWsKLS0tIHZUZXduQUlaNEQyTEdydEt5MnZy
            V2g3UzNQaHltM051aTcyNk03ZWpKeVkKG94JdLJTKn/rne+Hhw1kr9HvnlthfX40
            w0eYz+KAKdtsfiBkVLPOIpmGZQ4K281UrF8gSdFC1okFOJL2Z2Nrtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T13:57:59Z"
    mac: ENC[AES256_GCM,data:23xU4h/AWZW45m66mKKNpR//L9UtzUX52E5fGYtstidAWzB/9wH72AyP0M6BJhNus5Oqcb/r3ugvaTEC3RHCzBTS+yv+/cDHGwUNH6Cy5gstBs20ObXfI6yFt8DAxC72by7XzGURTCWkep8PnBvEOG1XDv/Wf+lHyHq17G/M80c=,iv:+DVWuW5+RvfAbSnwE2yfRPkI49JFDZrXyx5OKaLXY7E=,tag:NtzWaK3FxqTz0enWsP6oUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
