apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:MNId3rOAVNg/57FDLyA+,iv:kazHK108RMC+s81lvFy/hCNYws6hMlOIxNNfkLuvo1k=,tag:zAqLiQWk9tZIUeosfks0vA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:dA37+5LTZFRP2VFWOsNxV6lt/imfgCBKITHGoJvaQlGAB+Sv,iv:xzIZ00/zWrOwnF1846gr3M11GiSmD/i9EOSugTZUhLM=,tag:fT+i6lBLDkAbM/YdhUnqtQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:TF0bNlLsr94=,iv:LNRuROg/yrWnZy/SuwyUk/lMYJPee0JsFaBTYrgjJ3g=,tag:8X+NeQsQd4NhX8lkwI9vWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcjZuUEVsUkRRZU1Ndksw
            bGhZckhJVWRYZnVvM0pmSEh5TDI1dnU4bGw4CmIrWjN0TGx5eVdPN2hTUU9vZEk0
            emVxT1Z2YWlsY3JmclA0NWtSR1UweWsKLS0tIFR6M2Rjdmp1clpNTlhxeGdISzcz
            THNTemxFYjdadGVlTXpyLzE4c2FBalEKEmyX4F0A3yo4GAJ/a5N60r/6SAuhm3Bd
            HlDn9b2D12x/Sz6EYcr+Ze2Dt3g2PgV5EDvIU07oPEcMjr2YbRHb5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T13:57:59Z"
    mac: ENC[AES256_GCM,data:WVTkZAsG5o36U/MdMHpui8dQZOxBHQgzRrVVEmIk3iq1Sr1e7f+5ftaPP/h78efDdizCBagiSQeERS/3PjXcwKtJUP7LIa+/ixQMtKNApcE5NBeJCQ/VmvLMQOVZ+5ZivlV5DMiHyemvFb32dPn3eR/HQZctxSzPhXgRiL6XHAg=,iv:/sc/uwDJXABAfv58Zamc2amQT8dqBLf83t996DiAlzw=,tag:4gO1z3NNkOX3dw1o6UlK2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
