apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:WL87opl5XdtKkhPH,iv:Kd0yC6m7zbleaOBJl5P3u06GenSrPD8YeeUB2MpLV4g=,tag:8VuvJC6qWHwivOv6ZaOnpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWVRuYTFSOWZtK0dSZVUw
            WkVjMlh1YkdTQ3dudVd0Q2Vjems4dytqNVhzCnBIVkRtdVhrTjdSWGIydnIvTGx2
            OTREZS8zcksyWm0zUlZIZldzVXY5amcKLS0tIHp6eW4zMWpLREQxbXllUzVnQ3pY
            L3pRMjJqdzVGaEtycnFFTFBLdDhoVm8KicRcVYj1LYgTX4FtFIujkVQZQ3plm2zf
            NE+l9NtJdu4sK3+5xinaGnVf60znZwUu+oneQMUkjtio7RpLXqqeCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T14:17:42Z"
    mac: ENC[AES256_GCM,data:dV7e95HtaJMG+3V/2NScyVtg1+RrYEYBSKVf0FscfpHzW9+vhFF4MXTJk9lmBRdOtR/a1utUQlSoPPgDJqFgWGLvjBxtWXCIMVH/kdIJmkixbn+pVChXLv48cQmjuonYxmsa4OC2IKNBM9S+EOHWOjwZgJ9atNCaLMIIofz/aUU=,iv:VpV5WEtUwdKsiATTFVqTHLRs6WYudCJpPnLFWid3EAc=,tag:8baglcYMU2Y4/XIMIVjiew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
