apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:68R+KT+I7Yc4eCU/qqg9asVSDBJnXOBbR5Gr2ofJGq65sqBIU2qXrOzfpxLFXfhc2zkIfDjxIoO32LkVkikCMw==,iv:Ki1O9tNKcOcXV0N60O5sfuYHnpWFU3EPy/7Z2gPFy4s=,tag:am+fH7vhFZNVog3UJXAliA==,type:str]
    SECRET_PROXMOX_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:6ofgPis+Seg1j+V/qOX7dtL1sxPPscSrrAUoauky3N2ySjP0SgkBwAgkOMEbaOH2fF6qY05qkblT6UFxx9i63Q==,iv:wdU2TXbZtZJOKjwY3wl3hEImOXp+WGbA/BVC25xL0R8=,tag:mcCtXoLGYOrMdDv5WM1khg==,type:str]
    SECRET_SYNOLOGY_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:kzwGvjZagraZe4KwNQwGN4wJtR8/TxWcTGhgnZV7r1NhCviiShVMeptfIjLWX3jdFQEhs5anrD2tMTOJQfbgkA==,iv:KK+Iy3ZTwRPFr6Kc/M4ehbdD4UcDYAcqOtpPnUODbMg=,tag:I1JUr0AbuQ6PQGIZ6/37rg==,type:str]
    SECRET_PGADMIN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:wtyqUi14n6o7zg2hIm4Qe/E7ze3kjZEpUOwHiVqk7CWJN2N+2HJ4ORE4wwH13e3qrpBrBJSAdoc35t13Y82aOg==,iv:bBmshLbGBMrFO713uhVha6oJVfkC5CiDcFar9PMHx5I=,tag:SJbdtr8BXkn6+As/TaUR0A==,type:str]
    SECRET_CROWDSEC_ENROLL_KEY: ENC[AES256_GCM,data:WDlnQuqY42cyzZF9OrEUiS0AyGydSIDteA==,iv:1tFTwl4wcpOG3aPpcH/1A9J9n0PCnwXO+V+kWtCUH9g=,tag:JhLOT1zGWRTAO+ol/yJbhw==,type:str]
    SECRET_ALERTMANAGER_PUSHOVER_USER_KEY: ENC[AES256_GCM,data:xJg/FgKICFewJnX56wME/IlGuDit4zecEXS+Gmkv,iv:1PBbnWbo8XRU9iRJ9STf+7iAKt6Dy0tt3yHZyFggty4=,tag:tq5CfWZEBXpiSV+rIDpWgQ==,type:str]
    SECRET_ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:EMHvPAmY2Q2lDg8wlT/GgCJ/+tlda6o/Tv+EejfO,iv:dwBOYsadKQNl7j49HrVCdpofw74uKqFeakYdSbwzK0w=,tag:HLetXv1S/NWTP7PhUFTCkQ==,type:str]
    #ENC[AES256_GCM,data:W5AElNZ1xb3/FnLVTYqa3pYGPyqsMr0jXhH8QYvax6Ci/kqIvn9oV8Q/4eRFiOG4YtJqGkSffFPZibTTbvhF3yakmflT9eA+j3h+ya/DFm8NoBQ7a5LYkwDgBWkkNrz1dF08YxLI3Kk6pgym6a1IjjigHwE3kh5jf/ULFrzHzyx89E/tHB8f9N5FVqEU+aCiedttI+boXOKEqqTX1IdIFuAdU0tze/clFkhIT30rc8xF0lfF5FYKb8c7fkH6hF6wVIVEX7tqfnFXjIxreuc48NU=,iv:1WIgYRARLCEZQAth/yPySpVeH3VTBsu+goIZQmHKCfs=,tag:G5IT0uIKE6dMMj7Berg7DA==,type:comment]
    #ENC[AES256_GCM,data:hxFjcYzqA7EyaQOauFX2qSB9cK+fS62CHHklEKvLKkWKSZETrzbDFzlx9vjRlBUNKSRTrNo4zSrkFd/yoHMxnHPtPGdVolRviyrBo9x1wmi0ZzxlUiqWIWNcNo+6U960Tum41st7vAb3xK7nxx1aPtRDG8belem+aiaKwzjQ9M1NPWyM4Bg9730ahGbpSEOWXbAGZ8nGY7cRO3bI84G+KwUzzRtzj9S6IlH2p2T0oRXpL+CHYXjrBe/287xnfD37pSxAidyszbnaQZo02GQ=,iv:YubxMJ0GkHWnj+98VhIROqbA37yXhgaObsTO9LjjLH4=,tag:NPmyL6A5PEiDt2RyoOCeMg==,type:comment]
    #ENC[AES256_GCM,data:YD5BMETKN6vNBcTJA/JZqynx5n/XqZFm0wp/+7PhkPLECl0ZfKgh97aYZoyyLUFog3Jthf3vB6+SKZiVm8AXixSKIucCAMVjLU6FZIlsKS4Ne893MajZJBtNkFcwQ1BcjWW5dSjIO7mPtYLFopGFmdP9Mzlzp6quzFMQnxGM1HXJPUBy1q6LUo841KgF1/AmgH9mJd/Y+gdetmkP4qw9lLfpzg3+gA+m39dVwlzEmt4O/ZeOEA==,iv:M6gsAmVA4UJbhZ4iYfkpGThDAPDpW5PqXqTUjt4VUzM=,tag:s0srmK+ttxfQf28yidqc1g==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWlBjS1hYVzBlbFV1NDBo
            VHlLL2dhRFMzOXFXZ0k3QjQ1QnRuVTlDS1E0CmlRWnVWdmV2anJrdTBBNUkzWjRl
            NUtzU3VLWUtQRXFWa0I1T2NaV2RaZlEKLS0tIDhTZWZzclpFRHI1cng1Zk9lUVVZ
            a3IzTllaMGhsSVlTUTR1c1BaV003ZkUKaicdlolooSX43HmXMALnIx9LN1pjatIx
            rawmmexL4W6K3pujoGrr52RP9lkbxWSr1PLrtOjMkA+Ol2iJqFFLJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-11T17:14:38Z"
    mac: ENC[AES256_GCM,data:4kRPE1RuFSSOXUWLrApKPOwiuM/1NMLZOvGto4AsX+jGj6orCGH/8vQIrejBpto33/G3y8CIBG4pOPHxgfEEsc4Usmsd53vbqYpGUlD4sLYhdwMjex/zoah6DJwD559MhuDHyYwd0Kaw6yOfODA1+YS41tvB5QsxQJHKU6NrjQM=,iv:J+qhNDm49chiZ5BPus7/KSNB1XKj8Kp0y/MODn1n+F0=,tag:EDjtrUaUSN9Et3AI0Qg+fw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
