apiVersion: v1
kind: Secret
metadata:
    name: pgadmin
    namespace: database
type: Opaque
data:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:woE9OkfZAaNnqnnRvKFd95WwkOs=,iv:IKvzqJG3W2g9Li9Wy8onRdJwxoFCtfg9Pb5zoaFVTJY=,tag:VFF5hkNnGu2abygVRUPpiA==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:Z5gGvTYDOsh2pSaLOx0sSyyNgh0gcPITcaByyQ==,iv:govpzqPeL7NVGzpR/SkKp/3W2dH9yqDdX+3MZOsFckE=,tag:CGn0F8N3U49HnJLsqvGGvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUzgyclpjVEdmWDdQd0V5
            eUE2M0V1eGJ2U05sT21aZUtpeERJaVJWMUdFCnNEcW5BdE5TOVdCWjRQOWs4TmVz
            eWovMmg1ZURNbWs3b3p3bVJvZ281WU0KLS0tIGtDdUk0c0RYK2JRc3E5dGhyaHR1
            WkdqRU1WRzE4ZHdnRWJNNnZ0VGF6alkKablR/u6cQfeHZ7cHXy/oh9ShkN4ltbe+
            ibnzdmkgmuMT6Z6GEes76XSQKihjXCloq2JWJqb+AknV7O08kQ3Usw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-30T11:55:28Z"
    mac: ENC[AES256_GCM,data:faH26BaW3iusZt/aiI6WH7txprSoatnySHwDPwzj6yhPCiNR9FxXvjlNshJcDJ8QUD2xKg8yGm6t8/5IzPRx5vd/mJh0Je0QRXmyIHPprWPBUXaNfUUUl1zOYDy8Ucf+eQ2VfgCXGV9H/tn3/TZWAWnnNSl1tUP0RMvs+uFE/oY=,iv:L13+dpFQi2e6CksY6TYXS8avyN+rNQbby8ZBq+QYaIo=,tag:KCUUz0aUw2UW5epQFdNTbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
