apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
type: Opaque
data:
    password: ENC[AES256_GCM,data:8gg6wMRpix3iBv9C4IJP75cXSrp7DzUsbNqD0A==,iv:VCkuqVpRkCav5o/7LoZ0n5Rv+J4ZESUUjKMdGmGnbkU=,tag:LKBobl0Knlq2Dv8FAl8ytQ==,type:str]
    username: ENC[AES256_GCM,data:A9MD8hKSQ5YyCgnw,iv:dZqsJW7r5tkwds2ExEU37A0t2iUO83+iszPECe8ts0U=,tag:TBHkXzwYneFQdJ7mMav7yQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdGZZQmE4ZHZESEQ0TDMw
            NFhSL3hGcG5neGd2WU9oemZnNG9RNnNOaHpFCm5iaUZsNWRNd0lmYTQ2dlZDeXJR
            S25mWkU1b2Rhb1ppWnlzc3MyeGNtL1EKLS0tIEZBNnJ2WTVyckdrMGs4RjF2OUZV
            QjlYSDU5aE8xb3owYTl1UFdMWDVKSXMKHrCbkAEYye+3ixGAoFJOORciUv1yy3cW
            rAESrXSUPZoz6U/RIT6pNnNS7SRdDBtdHvBAoxzfjYg9i6KghJqarw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-30T13:01:03Z"
    mac: ENC[AES256_GCM,data:lXrF2Ycx4/utIgjIeV8H011xmK2xWSycrUiuZln8lEc4QlX2fX6crOBrJ8pb0xeoyanSgTXzDNiW3Dd0H2jEDPVgEWJDR9fNNHwsqy1wabGVzNm17sSNpu4Nv28sxqnOqBrFB0ycCA8RgGrb5fbKIzzeOTqggwMdIARuGDInSew=,iv:/EmkUnRCcPjuaERp+isSB0SYqbHL1dbiaG+gO3zj0vM=,tag:J+VY8JGZJjnPayALr6jdtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
