apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:pRsox7tWap+NuzWCtsL92f2CCdiEedtCXw4iEb8rG9nE3Vr5,iv:T7ZNYhi9tnk/MUxnfGBjIqWO6dE1aenmOGSqyG+qmQM=,tag:vruN15CYZ/v9G7BPhq02zA==,type:str]
    credentials.json: ENC[AES256_GCM,data:l5qgPZcPdlF9u3KvjnzNaAB/RLy5lPOZPyAnUZ6Hr+lXyatVDMMwajw/fdGSgMvfb26fGiwpawbRTAjFMMokTO3BPmeCNhAWEefqDmMDa03acn01mik64QywOAnggIeahHmQuzF5uDuRZiEVBc9dB+D59k5G0hfHNdteFRK50PEbn6oUme389QTGAfitEZ9o2p0SztGyIo76Vsuf0guN8waiSmN75jf0WdRjYQeRfA==,iv:23ndeFel5yfXbFxwJSIWnUPgpqxd+tWobdT15xFWn7M=,tag:MCvOmoTG4emNgAoKNiSz7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOG0xajU5ZWc2M2FOSUFL
            WjFNT0FyeGNTZjAyam5lZHZUbitBWjlmUUI0CmNJWTBMMFdnY0tlWDNMcnEzaHc1
            c2h2dTZsc0FvRlI4dndtei9TeW8vbGcKLS0tIHlxQU52S1pITjR6cE9vZUJRZWtw
            cUt3QXVNSDVRUTNPb2VlV2JrcW5MNHMKwe+D+h8qsfn0ex05O2LRHdZkHepcWdKi
            zfRH6F6F2W38ur930DhaSX6GO9PIzWwV0TiHnM7jK9ixsr/8MQMgnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T00:07:42Z"
    mac: ENC[AES256_GCM,data:7ny34VQPr0V7hhbzDtDpUebQZPcSd3YGyoatvIvyj7a8z90GW9ruiXd1lquhFdosRnwu0CZfoYsjrBY2LBG9rOYeRYuWSm+4liioWpj7feOh9+/PFJotVmPK/3jug/GixBrV9Nbw4uyxGLlmpunPGK1eDCa+ineaukDdLDCumKo=,iv:FUPfbhusctjZnuYTLPrjQThQ/MFa9lFiaqXT3TsTC6w=,tag:Q/XNwS1gkKM0JMlLDrWDvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
