apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Vq6wnbGmN6QB2GvWcMzwoQhMoengVUrCznQnLgpLnPn8mI2S,iv:rtDpHkBZrhPBLv1tJTLcj7AHvBGhfYcLbG7M93c8Xf4=,tag:UK0/P4Wrro7TPVlcrYNBKA==,type:str]
    credentials.json: ENC[AES256_GCM,data:oAU9lS34xcSU0XeAyy69AXgAC8xyCGVlyL8fDRU04HOvRhWZz2ZNkzHaJhebD4O1zWY+DzFGisyCzBKQlUCaaM9KrPsXhrc48xu/x5wliQ7whUOKamN29rjLTnIBcJ6xEfwuwgypx/40XT/5NHcYyWZ385ciX0orG0aRakFGWeZDqmrBjTyC5+4AfyCyXxj8NnaZApS0VAZO41zz49Gnp9AjVyOBPNk2S5u0cUHvqg==,iv:/pJthbYHhOOOLbQyaGtscLJ7fzgIy6pOYpfQpZ9z65I=,tag:qNAZ+6Q232iiS2kvr4yKkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTR2tjSEhxams3UGJmTkZG
            NVBnOEVOS01BSTYvcVRjNkNLZFU1MUZIanp3CmV4YjhSNmkvcXkwZlYxVWpRU2R1
            cDQvOVBBOXFWYllDWmpPSTMzSmtZU1UKLS0tIEZhNWdHeW9jVEhCWEFuWndrOXRm
            UmVNTXhoN2hFcytJaS93aVFKbzExb3cKL8Z0XiQEBRI8Hv6iGJsVXKBQlLnujLsy
            ZnZPOB9kEswrgNJEOH23Kit13ZvmiCXgcYDOiByYCiY5Pp9SdvquUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T08:44:51Z"
    mac: ENC[AES256_GCM,data:EtUmJuZeKyOLynXU/x91/ibxqIN3TO0FrDzkleHJU84aXn7vKe/MpjswPd6M33s7b8XO+nXaM8xFdSrVKAYb6ZV4gc9Zbr9fub6BFZ8T+WkHmKIFqgXTfg9TWZ3h9wc1eSVtcmxM7F1qGA7rgmEPwxnOY9nRcorH8BFRd1BtydQ=,iv:YcNl6nzH2omKa5kzhjq7S2n5rAgVJhyC20/xMXOjBBE=,tag:bwvjHA1s1o8Q7S78zmP2Dg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
