apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:dK+U2BAwGVYBKrp9qPu/x/yEdpv2A4GnyhX7BJMvPjW5OMxz,iv:DGYKrT4LSNeXqhDh5OD1/QyQrng6I747Av+BHwwfkbg=,tag:nvc/ORfj9wIkOOdV5Iiy4A==,type:str]
    credentials.json: ENC[AES256_GCM,data:MypBa2D2E25izAHYKVQWf31gL+PUg/BNY92Da0AH72r0a6cJtXf8AJDfgAAokkg2udjlUEOXcdtgP4IxWVXWJk8AKEjLYKbCR0gtk7zRm9042QMC0U9iM1m0JTx4NdR4EcA/YKtgX1H0jidFXgSFBb7bhG4q5pAp+fy/yOpiTfaAiQYQ3MFmQFyRwljqnrFCWhfEADRf8DJeZwab70XnXGlayaT2STdcYMNfXZdw9w==,iv:xXIfssVKgY29nkcG47OzqGGWLOrcKxFHdJy38VwnEhM=,tag:3Docojz2r/92zen7bBGZNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gs820l2axxmwkdwnks776d3z376jx8tmpnxmljlm2raz63pcksuspj2ctv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwU3dWYjMzRi96bk5oVmZh
            Rng2K2xLNlh6ZzlaS3Nna0l5aHVFVzFCZEhRClEyWWxmVDVSVGEyZVVnZ1VJQnVB
            WXNaRlRTVlhReVVnNEJISGExeCt6K0UKLS0tIFhDV3hicVlvd0lXTG9UQzdTN2hI
            WnFTelNqYVlMRmFNQXZieVE4UjNTKzAK23fS/J4zHcMQXGSDtNduClQZF8T5WTlH
            3o9uKnDfln8qD0OmUkm3LO33AhpczXKs/6kuo5784Eui3wqo3ZIzgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T09:09:54Z"
    mac: ENC[AES256_GCM,data:+X0qg+2M3lbzY+u2Lk/YwMLTbHiY24SPt8U3w0W3khbvA9BwNoHhXPH9q1oPJFXTybmlsqbqD8xTnIWiYfxhJvNuYIuHQa0x2SVlzpxWbwQzzfOAdkBNrGE3rLQBgMGm9hmmKImMGtPOpygdK+IsVKMwB7Zut9uoTH30rSKL/9A=,iv:prA8Uuu/92WJ6ak0tFOrHtop1nYAjT831V+vcwyfwps=,tag:kbAo8U3hwPwjQ7yfMrZNxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
