---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: authelia
        group: external
        url: https://auth.${SECRET_DOMAIN}
        interval: 1m
        client:
          dns-resolver: tcp://172.16.172.1:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
