---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-configmap
  namespace: selfhosted
data:
  # Configure application
  PAPERLESS_URL: "https://paperless.${SECRET_DOMAIN}"
  PAPERLESS_PORT: "8000"
  PAPERLESS_TIME_ZONE: "Europe/Berlin"
  PAPERLESS_WEBSERVER_WORKERS: "2"
  PAPERLESS_TASK_WORKERS: "2"

  # Configure LDAP
  PAPERLESS_LDAP_AUTH_ENABLED: "false"
  PAPERLESS_LDAP_AUTH_URL: "ldap://lldap.security.svc.cluster.local:389"
  PAPERLESS_LDAP_AUTH_SEARCH_BASE: "ou=people,dc=bjw-s,dc=dev"
  PAPERLESS_LDAP_UID_FORMAT: "uid=%s,ou=people,dc=bjw-s,dc=dev"
  PAPERLESS_LDAP_USER_GROUP: "cn=paperless,ou=groups,dc=bjw-s,dc=dev"
  PAPERLESS_LDAP_ADMIN_GROUP: "cn=paperless_admin,ou=groups,dc=bjw-s,dc=dev"
  PAPERLESS_LDAP_LLDAP_FIX: "true"

  # Configure folders
  PAPERLESS_CONSUMPTION_DIR: /data/nas/consume
  PAPERLESS_DATA_DIR: /data/local/data
  PAPERLESS_EXPORT_DIR: /data/nas/export
  PAPERLESS_MEDIA_ROOT: /data/local/media

  # Configure folder importer
  PAPERLESS_CONSUMER_POLLING: "60"
  PAPERLESS_CONSUMER_RECURSIVE: "true"
  PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"

  # Configure OCR
  PAPERLESS_OCR_LANGUAGES: eng deu
  PAPERLESS_OCR_LANGUAGE: eng

  # Configure redis integration
  PAPERLESS_REDIS: redis://paperless-redis.selfhosted.svc.cluster.local:6379

  # Configure user permissions
  USERMAP_GID: "65543"
